### PR TITLE
Update "contain" property to accept "inline-size"

### LINKED ISSUE #370: Support `contain: inline-size` property.
Relevant specification: [CSS Containment Module, Level 3](https://www.w3.org/TR/css-contain-3/#valdef-contain-inline-size)

The validator currently fails to recognize `inline-size` as a valid value for the `contain` property. When invoked via the Nu HTML Checker, the CSS validator returns the message:

<pre>
<samp>"CSS: “contain”: “inline-size” is not a “contain” value."</samp>
</pre>

This feature is implemented in WebKit, Firefox, and Chromium.

- [WebKit bug 236354](https://bugs.webkit.org/show_bug.cgi?id=236354)
- [Mozilla bug 1755565](https://bugzilla.mozilla.org/show_bug.cgi?id=1755565)

### PR DESCRIPTION
**Pull request by Seirdy**
Closes #370

### CODE REVIEW

**Comment by ylafon** [comment]
Do you have a pointer to the specification? It is useful as a reference (see at the top of the file), and also to ensure that the patch is the right one.
Thanks!

**Comment by Seirdy** [comment]
Spec: https://www.w3.org/TR/css-contain-3/#valdef-contain-inline-size

**Comment by Seirdy** [comment]
On Sun, Aug 07, 2022 at 12:23:43AM -0700, Yves Lafon wrote:
>Do you have a pointer to the specification? It is useful as a reference (see at the top of the file), and also to ensure that the patch is the right one.

Added a ***@***.***" with a link to the specification near the top.

-- 
Seirdy (https://seirdy.one)

**Comment by ylafon** [comment]
Looking at https://www.w3.org/TR/2022/WD-css-contain-3-20220818/#contain-property it seems that another check is required.
Note that the grammar changed, and this is the reason we try to implement only what is somehow stable.

**Comment by ylafon** [comment]
Closed per 78ebb170c9c276b99ce3fc43e7e508cdf9b4df6a

**Pull request closed without merging**
