### PR TITLE
W3C Bugzilla => GitHub Issues

### PR DESCRIPTION
**Pull request by cvrebert**
At least, I'm assuming that's the plan here?

### CODE REVIEW

**Comment by cvrebert** [comment]
Resolved merge conflicts.

**Comment by sideshowbarker** [comment]
> At least, I'm assuming that's the plan here?

Not sure we have agreement about that yet. At least need to wait til @ylafon weighs in on that.

**Comment by sideshowbarker** [comment]
The commit with the change to Unix line endings should be in a separate PR.

**Comment by ylafon** [comment]
I'm all for leaving bugzilla behind. The only issue is... Do we start from a blank state or do we try to import issues that needs to be curated?

**Comment by cvrebert** [comment]
Your call. If you wish to leave the legacy issues where they are, I'm happy to rework this pull request to retain mentions of the legacy bugzilla.

**Comment by sideshowbarker** [comment]
> If you wish to leave the legacy issues where they are, I'm happy to rework this pull request to retain mentions of the legacy bugzilla.

It seems like for now, the PR should just do that. And, after we have a pointer to this issue tracker actually deployed in the live W3C validator instance, we can close the bugzilla component to new bugs.

**Comment by sideshowbarker** [comment]
> Do we start from a blank state or do we try to import issues that needs to be curated

I would suggest we must look at the open bugs case by case, and any that somebody is willing to write a patch for, they just open here as PRs, and change to status of the bug to resolve-moved.

And for selected other bugs that we think we might have some good chance to get patches for here at github from contributors, it may be worth it to move a few of those to being issues here.

But I don't think we should move all the bugs en masse.

**Comment by cvrebert** [comment]
@sideshowbarker Okay, done. \*wipes brow*

**Comment by sideshowbarker** [comment]
Looks like we have agreement on making the github issue tracker the place to report new bugs, so I’ll go ahead and merge this.

**Pull request merged**
