### PR TITLE
Allow CSS custom properties (without checking)

### PR DESCRIPTION
**Pull request by sideshowbarker**
This change is a temporary workaround that adds an interim/initial/partial level
of support for handling CSS custom properties and the `var(...)` function. The
intent is that we’ll add full support later, and then at that time back this
change out — or else at least just use it as a starting point for full support.

This change simply allows declarations to contain custom property names (that
is, identifiers starting with two dashes) and to contain the `var(...)` function
(with a custom property name as the first argument). Beyond that, it doesn’t add
any checking to report an error if a `var(...)` function contains a custom
property name that the stylesheet hasn’t actually defined, and no checking to
report an error if a particular property has an expression with a `var(...)`
function which resolves to a value that’s not allowed for that property.

Addresses https://github.com/w3c/css-validator/issues/111

### CODE REVIEW

**Comment by najamelan** [comment]
Could this be deployed? My school insists our code passes the validator which means I might have to rewrite my project without CSS variables because the validator is not up to date...

**Comment by saschanaz** [comment]
It seems there are a few remaining issues e.g. #295 and #303. Probably better to keep tracking it there.

**Comment by najamelan** [comment]
@saschanaz Thanks, I hadn't seen those issues. They don't seem to mention any reason not to deploy an update to the live validator however since this was merged 10 months ago it looks like all that is missing as a roll out.

**Comment by saschanaz** [comment]
The patch itself is deployed and the validator can read custom properties. Try https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Fyari-demos.prod.mdn.mozit.cloud%2Fen-US%2Fdocs%2FWeb%2FCSS%2FUsing_CSS_custom_properties%2F_sample_.First_steps_with_custom_properties.html&profile=css3svg&usermedium=all&warning=1&vextwarning=&lang=en for example.

**Comment by najamelan** [comment]
@sashanaz My apologies. I got confused. I get errors on code like this:

```css
.search
{
   --search-height: 14.5rem;
   --search-radius: calc( var(--search-height) / 3 );
}
```
Since it throws warnings for the variables and the line here throws an error right after the `var()` I thought it was related. It looks like it's rather choking on the mathematical operator combined with a variable. It does not have trouble with `calc( 5rem / 3 );`. It does not like other arithmetic operators either.

AFAICT This is correct CSS code. Maybe that's an issue with this PR not supporting operators on variables?

**Comment by najamelan** [comment]
Looking through the diffs here it's quite hard to tell what's going on not knowing the grammar syntax used. Maybe @sideshowbarker can clarify whether this could was intended to pass or not...

**Comment by sideshowbarker** [comment]
> ```css
> .search
> {
>    --search-height: 14.5rem;
>    --search-radius: calc( var(--search-height) / 3 );
> }
> ```

That’s valid per spec.

The fact that the validator doesn’t recognize it as valid is a bug in the validator.

There are many such cases of valid CSS using custom properties and certain functions that are known to fail in the validator. The cause is that the validator doesn’t actually yet have support for custom properties.

And the solution is that someone needs to update the validator code to add real support for custom properties. Nobody is currently working on that, though. So I don’t expect anything to change around this any time soon.

**Comment by najamelan** [comment]
@sideshowbarker Thanks for clarifying. Hopefully my evaluator will let me pass the exercise with css variables thanks to your comment. Btw just want to say, I :sparkling_heart: MDN. Many thanks for your hard work.

**Pull request merged**
