### PR TITLE
Optionally treat most legacy IE filters as only warnings

### PR DESCRIPTION
**Pull request by cvrebert**
When the "Treat Vendor Extensions as warnings" option is enabled, this PR treats [legacy IE `filter` values](https://msdn.microsoft.com/library/ms530752%28v=vs.85%29.aspx) as warnings instead of errors, thus fixing part of #10. This makes them get treated basically the same as their `-ms-filter` equivalents. If you'd prefer this to be controlled by some other flag instead, let me know.

Adds scaffolding for #25 by moving `filter` from SVG into CSS3. (It seems to technically be ["CSS4"](https://drafts.csswg.org/css-2015/#css-level-4), but the validator only seems to have an incomplete stub for CSS4 at the moment.)

### CODE REVIEW

**Comment by cvrebert** [comment]
@ylafon Your thoughts on this?

**Comment by cvrebert** [comment]
@ylafon Any feedback?

**Comment by ylafon** [comment]
It is ok (needs some minor tweaks).
However the parsing of function() is missing things that would make those work.
For example, filter: alpha(opacity=50); fails as opacity=50 is not properly parsed as of now, it triggers wrongly a ParseError. I'll merge this when the function() parse will be better defined.

**Comment by cvrebert** [comment]
**Thank you!** :bow:

**Comment by ylafon** [comment]
Thanks to you! You pushed me to dive in the parser again :cry:

**Comment by cvrebert** [comment]
Glad you made it out alive :smile:

**Pull request merged**
